# Python 3.10 slim image kullanıyoruz
FROM python:3.10-slim

# Çalışma dizinini oluşturuyoruz
WORKDIR /app

# Önce requirements.txt dosyasını kopyala
COPY requirements.txt .

# Paketleri yükle
RUN pip install --no-cache-dir -r requirements.txt

# Proje dosyalarını kopyala
COPY . .

# Portu environment olarak belirt (istersen değiştirebilirsin)
ENV PORT 8080

# Gunicorn ile Django uygulamasını başlat
CMD ["gunicorn", "origin.wsgi:application", "--bind", "0.0.0.0:8080"]
