# Generated by Django 5.1.5 on 2025-01-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeldata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='channeldata',
            name='updated_at',
        ),
    ]
