# Generated by Django 5.1.5 on 2025-01-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_channeldata_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeldata',
            name='channel_name',
        ),
    ]
