# Generated by Django 5.1.5 on 2025-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_scraperlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_category', models.CharField(max_length=255)),
                ('selective_part', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('author_name', models.CharField(blank=True, default='Toplam Yazar', max_length=255, null=True)),
                ('author_follower_count', models.IntegerField(default=0)),
                ('body', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_time', models.DateField()),
            ],
            options={
                'verbose_name': 'Son 7 Günlük Veri',
                'verbose_name_plural': 'Son 7 Günlük Veriler',
            },
        ),
    ]
