# Generated by Django 5.1.5 on 2025-02-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_latestdatatable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latestdatatable',
            old_name='author_follower_count',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='latestdatatable',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='latestdatatable',
            name='body',
        ),
        migrations.RemoveField(
            model_name='latestdatatable',
            name='link',
        ),
        migrations.AddField(
            model_name='latestdatatable',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
