# Generated by Django 5.1.5 on 2025-02-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_author_follower_count_latestdatatable_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestdatatable',
            name='author',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='latestdatatable',
            name='total',
            field=models.IntegerField(),
        ),
    ]
