# Generated by Django 5.1.5 on 2025-02-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_latestdatatable_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestdatatable',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
