# Generated by Django 5.1.5 on 2025-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_latestdatatable_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.URLField(blank=True, null=True)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
                ('following_count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nick', models.CharField(blank=True, max_length=255, null=True)),
                ('brands', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('favourite_count', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('quote_count', models.IntegerField(blank=True, null=True)),
                ('reply_content', models.TextField(blank=True, null=True)),
                ('retweet_count', models.IntegerField(blank=True, null=True)),
                ('view_count', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('selective_part', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
