# Generated by Django 5.1.5 on 2025-02-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_socialmediapost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestDataTable',
            new_name='Latest7Days',
        ),
        migrations.RenameModel(
            old_name='ChannelData',
            new_name='LatestData',
        ),
        migrations.RenameModel(
            old_name='SocialMediaPost',
            new_name='MostSharedContent',
        ),
    ]
