# Generated by Django 5.1.5 on 2025-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_latestdatatable_latest7days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostsharedcontent',
            name='source_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
